[package]
name = "starship_module_config_derive"
version = "0.1.1"
edition = "2018"
authors = ["Matan Kushner <hello@matchai.me>"]
homepage = "https://starship.rs"
documentation = "https://starship.rs/guide/"
repository = "https://github.com/starship/starship"
readme = "README.md"
license = "ISC"
keywords = ["prompt", "shell", "bash", "fish", "zsh"]
categories = ["command-line-utilities"]
description = """
The minimal, blazing-fast, and infinitely customizable prompt for any shell! â˜„ğŸŒŒï¸
"""
exclude = ["docs/**/*"]

[lib]
name = "starship_module_config_derive"
proc-macro = true

[dependencies]
proc-macro2 = "~1"
quote = "~1"
syn = "~1"
