format = """
[\ue0c7](#D65D0E)\
$username\
[î‚°](bg:#98971A fg:#D65D0E)\
$directory\
[î‚°](fg:#98971A bg:#689D6A)\
$java\
$scala\
[î‚°](fg:#689D6A bg:#D79921)\
$nodejs\
$python\
$ruby\
[î‚°](fg:#D79921 bg:#B16286)\
$git_branch\
$git_status\
[î‚°](fg:#B16286 bg:#458588)\
$time\
[\ue0c6 ](fg:#458588)\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#D65D0E"
style_root = "bg:#D65D0E"
format = '[ğŸ•  $user ]($style)'

[directory]
style = "bg:#98971A"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_branch]
symbol = "ğŸŒ± "
style = "bg:#B16286"
truncation_length = 8
truncation_symbol = "â€¦"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#B16286"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](fg:#282828 bg:#B16286)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
format = '[$all_status$ahead_behind ]($style)'

[java]
symbol = "î‰– "
style = "bg:#689D6A"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = "îˆ¾ "
style = "bg:#D79921"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#689D6A"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "îœ¼"
style = "bg:#D79921"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#D79921"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#458588"
format = '[ â™¥ï¸  $time ]($style)'
