"$schema" = 'https://starship.rs/config-schema.json'

# Configures the format of the prompt.
format = """
[](color_green)\
$os\
$username\
[](bg:color_orange fg:color_green)\
$directory\
[](fg:color_orange bg:color_cyan)\
$git_branch\
$git_status\
[](fg:color_cyan bg:color_blue)\
$c\
$dotnet\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$elixir\
$elm\
$gradle\
$julia\
$nim\
$scala\
[](fg:color_blue bg:mono3)\
$docker_context\
[ ](mono3)\
$fill\
[ ](mono4)\
$time\
$battery\
[ ](mono4)\
$line_break$character"""

# Sets the palette to "one_dark".
palette = 'one_dark'

# Sets the colors of the "one_dark" palette.
[palettes.one_dark]
mono0 = '#d7dae0' # terminal white, from the One Dark Pro VSCode theme.
mono1 = '#abb2bf' # syntax_fg.
mono2 = '#828997'
mono3 = '#5c6370'
mono4 = '#3f4451' # terminal black, from the One Dark Pro VSCode theme.
color_red0 = '#e06c75'
color_red1 = '#be5046'
color_green = '#98c379'
color_yellow = '#e5c07b'
color_blue = '#61afef'
color_purple = '#c678dd'
color_cyan = '#56b6c2'
color_orange = '#d19a66'
syntax_fg = '#abb2bf'
syntax_bg = '#282c34'
color_bg2 = '#665c54'
syntax_gutter = '#647382'
syntax_accent = '#528cff'

# Module that displays the current OS.
[os]
disabled = false # Disabled by default
style = "bg:color_green fg:syntax_bg"
format = '[ $symbol ]($style)'

# Sets custom symbols for each OS.
[os.symbols]
Alpine = ""
Amazon = ""
Android = "󰀲"
Arch = ""
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
FreeBSD = "󰣠"
Gentoo = "󰣨"
Illumos = ""
Linux = "󰌽"
Macos = "󰀵"
Manjaro = "󱘊"
Mint = "󰣭"
NixOS = "󱄅"
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Redox = "R"
Solus = ""
SUSE = ""
Ubuntu = "󰕈"
Unknown = ""
Windows = "󰍲"

# Module that displays the current username.
[username]
show_always = true
style_user = "bold bg:color_green fg:syntax_bg"
style_root = "bold bg:color_green fg:syntax_bg"
format = '[ $user ]($style)'

# Module that displays the current directory.
[directory]
style = "italic fg:syntax_bg bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Sets the custom symbols for directories.
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# Module that displays the current git branch.
[git_branch]
symbol = ""
style = "bg:color_cyan"
format = '[[ $symbol $branch ](fg:syntax_bg bg:color_cyan)]($style)'

# Module that displays the current git status.
[git_status]
style = "bg:color_cyan"
format = '[[($all_status$ahead_behind )](fg:syntax_bg bg:color_cyan)]($style)'

# Language specific modules
[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[dotnet]
symbol = "󰪮"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[php]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[kotlin]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[haskell]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[python]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:syntax_bg bg:color_blue)]($style)'

[elixir]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_blue)]($style)'

[elm]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_blue)]($style)'

[gradle]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_blue)]($style)'

[julia]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_blue)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:color_blue"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_blue)]($style)'

[scala]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol ($version) ](fg:syntax_bg bg:color_blue)]($style)'

# Module that displays the docker context.
[docker_context]
symbol = " "
style = "bg:mono3"
format = '[[ $symbol( $context) ](fg:syntax_fg bg:mono3)]($style)'

# Module that fills the space between the left and right segments.
[fill]
symbol = " "

# Module that displays the time.
[time]
disabled = false # Disabled by default
use_12hr = true # Disable for 24h format without seconds
style = "bg:mono4"
format = '[[ 󰥔 $time ](fg:syntax_fg bg:mono4)]($style)'

# Module that displays the battery level and status.
[battery]
format = '[$symbol $percentage ]($style)'

# Battery symbols and colors for each threshold.
[[battery.display]]
threshold = 10
style = "bold bg:mono4 fg:color_red1"
discharging_symbol = "󰁺"
charging_symbol = "󰢜"

[[battery.display]]
threshold = 20
style = "bold bg:mono4 fg:color_red0"
discharging_symbol = "󰁻"
charging_symbol = "󰂆"

[[battery.display]]
threshold = 30
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁼"
charging_symbol = "󰂇"

[[battery.display]]
threshold = 40
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁽"
charging_symbol = "󰂈"

[[battery.display]]
threshold = 50
style = "bold bg:mono4 fg:color_yellow"
discharging_symbol = "󰁾"
charging_symbol = "󰢝"

[[battery.display]]
threshold = 60
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰁿"
charging_symbol = "󰂉"

[[battery.display]]
threshold = 70
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂀"
charging_symbol = "󰢞"

[[battery.display]]
threshold = 80
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂁"
charging_symbol = "󰂊"

[[battery.display]]
threshold = 90
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰂂"
charging_symbol = "󰂋"

[[battery.display]]
style = "bold bg:mono4 fg:color_green"
discharging_symbol = "󰁹"
charging_symbol = "󰂅"
threshold = 100

# New line character
[character]
success_symbol = '[󰅂](bold fg:syntax_accent)'
error_symbol = '[](bold fg:color_red1)'
vimcmd_symbol = '[󰅁](bold fg:syntax_accent)'
vimcmd_replace_one_symbol = '[󰅁](bold fg:color_purple)'
vimcmd_replace_symbol = '[󰅁](bold fg:color_purple)'
vimcmd_visual_symbol = '[󰅁](bold fg:color_yellow)'
