right_format = """
[${custom.leftcap}](fg:tooling_hex bg:none)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[${custom.rightcap}](fg:tooling_hex bg:none) \
"""

format = """
[](user_os_hex)\
$os\
$username\
[](bg:path_hex fg:user_os_hex)\
$directory\
[](fg:path_hex bg:git_hex)\
$git_branch\
$git_status\
[](fg:git_hex bg:tooling_hex)\

[](fg:tooling_hex bg:endcap_hex)\
[](fg:endcap_hex bg:none)  \
 $nix_shell\
${custom.dualline}[](fg:time_hex)\
$time\
[ ](fg:time_hex)\
"""

# blank line at the start of the prompt
add_newline = true

palette = 'pastel'

[palettes.pastel]
user_os_hex = '#9A348E'
tooling_hex = '#86BBD8'
path_hex = '#DA627D'
git_hex = '#FCA17D'
time_hex = '#33658A'
endcap_hex = '#06969A'

[palettes.tokyo]
user_os_hex = '#a3aed2'
tooling_hex = '#a3aed2'
path_hex = '#769ff0'
git_hex = '#394260'
time_hex = '#1d2230'
endcap_hex = '#769ff0'

[custom.dualline]
when = true
format = " \n "

# one can replace the caps:
#     
[custom.leftcap]
when = true
format = ''
[custom.rightcap]
when = true
format = ''

# You can also replace your username with a neat symbol like   or disable thiswhen = true
# and use the os module below
[username]
show_always = true
style_user = "bg:user_os_hex"
style_root = "bg:user_os_hex"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:user_os_hex"
disabled = true

[directory]
style = "bg:path_hex"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[docker_context]
disabled = false
symbol = " "
style = "bg:endcap_hex"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:git_hex"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:git_hex"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:tooling_hex"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:time_hex"
format = '[ $time ]($style)'
