format = '''
[â”Œ](fg:red)$status$os$hostname$time$directory$git_branch$git_status
[â””â”€â”€â•¼](fg:red)$username[\$ ](fg:yellow)
'''

[status]
style = 'fg:white'
symbol = 'âœ—'
format = '[\[](fg:red)[$symbol]($style)[\]](fg:red)'
disabled = false

[username]
style_user = 'green'
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "fg:cyan"
format = '[\[](fg:red)[$ssh_symbol$hostname]($style)[\]](fg:red)'

[directory]
style = "fg:purple"
format = '[â”€\[](fg:red)[$path]($style)[\]](fg:red)'
truncate_to_repo = false

[git_branch]
symbol = "ğŸ´"
style = "fg:blue"
format = '[â”€\[](fg:red)[$symbol $branch]($style)'

[git_status]
style = "fg:yellow"
format = '([$all_status$ahead_behind]($style))[\]](fg:red)'
staged = '[++\($count\)](green)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[time]
style = "fg:yellow"
format = '[â”€\[](fg:red)[$time]($style)[\]](fg:red)'
time_format = '%H:%M-%d/%m'
disabled = false
