format = """
[â–‘â–’â–“](blurple)\
$os\
$username\
[î‚´](bg:blue fg:blurple)\
$directory\
[î‚´](fg:blue bg:blurple_dark)\
$git_branch\
$git_status\
[î‚´](fg:blurple_dark bg:blurple_darkest)\
$java\
$nodejs\
$python\
$rust\
$golang\
$php\
$c\
$elixir\
$elm\
$gradle\
$haskell\
$julia\
$nim\
$scala\
[î‚´](fg:blurple_darkest bg:black)\
$time\
[î‚´ ](fg:black)\
$line_break$character"""

# Set Tokyo Night as custom color palette
# You can also use the legacy version of the palette by setting the palette to 'tokyo_night_legacy'
palette = 'tokyo_night'

# Define custom colors
# Tokyo Night palette (consistent with the VSCode theme)
[palettes.tokyo_night]
blurple = "#a9b1dc"
blurple_darker = "#9aa5ce"
blurple_dark = "#565f89"
blurple_darkest = "#414868"
white = "#c0caf5"
black = "#24283b"
night = "#1a1b26"
blue = "#7aa2f7"

# Tokyo Night Legacy palette (consistent with the old Starship preset)
[palettes.tokyo_night_legacy]
blurple = "#a3aed2"
blurple_darker = "#7d8cad"
blurple_dark = "#394260"
blurple_darkest = "#212736"
white = "#e3e5e5"
black = "#1d2230"
night = "#090c0c"
blue = "#769ff0"

# You can also replace your username with a neat symbol like ï„   or disable this
[username]
show_always = true
style_user = "bg:blurple fg:night"
style_root = "bg:blurple fg:night"
format = '[ $user ]($style)'
disabled = true # Disabled by default

# Represents the current operating system
[os]
format = "[ $symbol]($style)"
style = "bg:blurple fg:night"
disabled = false # Disabled by default

# Define custom symbols for operating systems
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ó°€² "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ó°£š "
EndeavourOS = "ïŒ¢ "
Fedora = "ó°£› "
FreeBSD = "ó°£  "
Gentoo = "ó°£¨ "
Illumos = "ïŒ¦ "
Linux = "ó°Œ½ "
Macos = "ó°€µ "
Manjaro = "ó±˜Š "
Mint = "ó°£­ "
NixOS = "ó±„… "
OpenBSD = "ïŒ¨ "
openSUSE = "ïŒ” "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ó±„› "
RedHatEnterprise = "ó±„› "
Redox = "ğŸ§ª "
Solus = "ïŒ­ "
SUSE = "ïŒ” "
Ubuntu = "ó°•ˆ "
Unknown = "ï™ "
Windows = "ó°² "

# Represents the current directory
[directory]
style = "fg:white bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Define custom symbols for directories
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

# Represents the current git branch
[git_branch]
symbol = "ï˜"
style = "bg:blurple_dark"
format = '[[ $symbol $branch ](fg:blue bg:blurple_dark)]($style)'

# Represents the current git status
[git_status]
style = "bg:blurple_dark"
format = '[[($all_status$ahead_behind )](fg:blue bg:blurple_dark)]($style)'

# Define custom symbols for languages
[java]
symbol = "î‰–"
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[python]
symbol = "îœ¼"
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[rust]
symbol = "î¨"
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[golang]
symbol = "î˜§"
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[c]
symbol = "î˜ "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[gradle]
symbol = "î™  "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[haskell]
symbol = "î· "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

[scala]
symbol = "îœ· "
style = "bg:blurple_darkest"
format = '[[ $symbol ($version) ](fg:blue bg:blurple_darkest)]($style)'

# Represents the current time
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:black"
format = '[[ ïº $time ](fg:#a0a9cb bg:black)]($style)'
