'$schema' = 'https://starship.rs/config-schema.json'

[aws]
symbol = ' '

[azure]
symbol = ' '

[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂌 '
unknown_symbol = '󰂑 '
empty_symbol = '󰂎 '

[bun]
symbol = ' '

[c]
symbol = ' '

[cmake]
symbol = ' '

[container]
symbol = ' '

[cpp]
symbol = ' '

[crystal]
symbol = ' '

[dart]
symbol = ' '

[deno]
symbol = ' '

[directory]
read_only = ''

[docker_context]
symbol = ' '

[dotnet]
symbol = '󰪮 '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[erlang]
symbol = ' '

[fennel]
symbol = ' '

[fortran]
symbol = ' '

[fossil_branch]
symbol = ' '

[gcloud]
symbol = ' '

[git_branch]
symbol = ' '

[git_commit]
tag_symbol = '󰓹 '

[git_status]
conflicted = ''
ahead = ''
behind = ''
diverged = '󱡷'
renamed = '󰏫'
untracked = ''
deleted = ''

[golang]
symbol = ' '

[gradle]
symbol = ' '

[guix_shell]
symbol = ' '

[haskell]
symbol = ' '

[haxe]
symbol = ' '

[helm]
symbol = ' '

[hg_branch]
symbol = ' '

[hostname]
ssh_symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[kotlin]
symbol = ' '

[kubernetes]
symbol = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = ' '

[nim]
symbol = ' '

[nix_shell]
symbol = ' '

[nodejs]
symbol = ' '

[ocaml]
symbol = ' '

[openstack]
symbol = ' '

[os.symbols]
Alpine = ' '
AlmaLinux = ' '
Amazon = ' '
Android = ' '
AOSC = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
Elementary = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = ' '
Gentoo = ' '
Illumos = ' '
Ios = '󰀷 '
Kali = ' '
Linux = ' '
Macos = ' '
Manjaro = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
Nobara = ' '
OpenBSD = ' '
openSUSE = ' '
OracleLinux = ' '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
RockyLinux = ' '
Redox = '󰀘 '
Solus = ' '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Uos = 'Uos '
Void = ' '
Windows = '󰍲 '
Zorin = ' '

[package]
symbol = '󰏗 '

[perl]
symbol = ' '

[pulumi]
symbol = ' '

[purescript]
symbol = ' '

[php]
symbol = ' '

[pijul_channel]
symbol = ' '

[python]
symbol = ' '

[rlang]
symbol = '󰟔 '

[ruby]
symbol = ' '

[rust]
symbol = '󱘗 '

[scala]
symbol = ' '

[spack]
symbol = ' '

[status]
symbol = ''
not_executable_symbol = '󰜺'
not_found_symbol = ''
sigint_symbol = ''
signal_symbol = '󱐋'

[sudo]
symbol = ''

[swift]
symbol = ' '

[terraform]
symbol = ' '

[typst]
symbol = ' '

[vagrant]
symbol = ' '

[vlang]
symbol = ' '

[xmake]
symbol = ' '

[zig]
symbol = ' '
