"$schema" = 'https://starship.rs/config-schema.json'

[battery]
full_symbol = "‚Ä¢ "
charging_symbol = "‚á° "
discharging_symbol = "‚á£ "
unknown_symbol = "‚ùì "
empty_symbol = "‚ùó "

[erlang]
symbol = "‚ìî "

[fortran]
symbol = "F "

[git_remote]
symbol = "remote "
no_remote_symbol = "no-remote "

[git_remote.providers]
"github.com" = "gh "
"gitlab.com" = "gl "
"bitbucket.org" = "bb "
"codeberg.org" = "cb "
"sr.ht" = "srht "
"dev.azure.com" = "az "

[nodejs]
symbol = "[‚¨¢](bold green) "

[pulumi]
symbol = "üßä "

[typst]
symbol = "t "
