format = """
[î‚¶](#329da8)\
$username\
[î‚°](bg:#5E81AC fg:#2E3440)\
$directory\
[î‚°](fg:#5E81AC bg:#88C0D0)\
$python$conda\
[î‚°](fg:#88C0D0 bg:#8FBCBB)\
$git_branch$git_status\
[î‚°](fg:#8FBCBB bg:#81A1C1)\
$time\
[î‚°](fg:#81A1C1)\
$line_break$character
"""

[username]
show_always = true
style_user = "bg:#2E3440 fg:#FFFFFF"
format = '[ ïŠ½ $user ]($style)'

[directory]
style = "bg:#5E81AC fg:#ECEFF4"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
fish_style_pwd_dir_length = 3

[directory.substitutions]
"~" = "ï€• "
"Documents" = "ó°ˆ™ Docs"
"Downloads" = "ï€™ DL"
"Projects" = "î¬° Proj"
"Music" = "ó°š Music"
"Pictures" = "ï€¾ Pics"
"Desktop" = "ï„ˆ Desk"

[python]
symbol = "îœ¼"
style = "bg:#88C0D0 fg:#2E3440"
format = '[ $symbol ($virtualenv) ]($style)'
pyenv_version_name = false

[conda]
symbol = "ó±”"
style = "bg:#88C0D0 fg:#2E3440"
format = '[ $symbol $environment ]($style)'
ignore_base = false

[git_branch]
symbol = "îœ¥"
style = "bg:#8FBCBB fg:#2E3440"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#8FBCBB fg:#2E3440"
format = '[$all_status ]($style)'
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
renamed = "ğŸ”€"
deleted = "âœ˜"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#81A1C1 fg:#2E3440"
format = '[ğŸ•’ $time ]($style)'

[line_break]
disabled = false

[character]
success_symbol = "[â¯â¯](bold green)"
error_symbol = "[â¯!](bold red)"
vimcmd_symbol = "[â®](green)"

