"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#6F2770)\
$os\
$username\
[](bg:#9A0F5A fg:#6F2770)\
$directory\
[](fg:#A0135E bg:#C96657)\
$git_branch\
$git_status\
[](fg:#C96657 bg:#5C8FA3)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#5C8FA3 bg:#056871)\
$docker_context\
[](fg:#056871 bg:#26475C)\
$time\
[ ](fg:#26475C)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#FFFFFF bg:#6F2770"
style_root = "fg:#FFFFFF bg:#6F2770"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:#FFFFFF bg:#6F2770"
disabled = true # Disabled by default

[directory]
style = "fg:#FFFFFF bg:#A0135E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#FFFFFF bg:#056871"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#FFFFFF bg:#C96657"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#FFFFFF bg:#C96657"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#FFFFFF bg:#5C8FA3"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#FFFFFF bg:#26475C"
format = '[ ♥ $time ]($style)'

