blank_issues_enabled: false
contact_links:
  - name:  â“ Ask a question
    url: https://github.com/starship/starship/discussions/new
    about: Ask questions and discuss with other community members
