name: Auto-merge Dependabot PRs
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  auto_merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-merge: "minor"
          merge-method: "squash"
